package main

import (
	"encoding/csv"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"maps"
	"os"
	"sort"
	"strings"

	"github.com/client9/chunky"
)

func main() {
	csvMode := flag.Bool("csv", false, "output CSV (word,tag) instead of JSON")
	goMode := flag.Bool("go", false, "output Go source for tok/lexicon_gen.go instead of JSON")
	flag.Parse()

	// Read from Stdin
	b, err := io.ReadAll(os.Stdin)
	if err != nil {
		log.Fatalf("unable read input: %s", err)
	}

	// unserialize into wordmap
	var wordmap map[string][]string
	err = json.Unmarshal(b, &wordmap)
	if err != nil {
		log.Fatalf("unable to unmarshall Brown JSON data: %s", err)
	}

	countTotal := 0
	countUni := 0

	// convert tags — each word gets a bitfield OR of all observed tags
	outmap := make(map[string]chunky.Tag, len(wordmap))
	for word, btags := range wordmap {

		// Ignore words with upper case letters.
		if strings.ContainsAny(word, "ABCDEFGHIJKLMNOPQRSTUVWXYZ") {
			continue
		}

		// contractions and possessives don't go in the lexicon dictionary.
		if strings.Contains(word, "'") {
			continue
		}

		// some junk in corpus
		if strings.ContainsAny(word, "{*") {
			continue
		}

		// things with numbers are done elsewhere
		if strings.ContainsAny(word, "0123456789") {
			continue
		}

		var combined chunky.Tag
		for _, bt := range btags {
			// these are slang words or contractions
			if strings.Contains(bt, "+") {
				continue
			}
			// junk in corpus
			if bt == "NIL" {
				continue
			}
			udtag := chunky.TagFromBrownTag(bt)
			if udtag == chunky.TagUNK {
				log.Printf("brown tag of %s didn't remap for word %q", bt, word)
			}
			combined |= udtag
		}
		if combined == 0 {
			// most non-English words and junk
			log.Printf("skipped word %q: no tags", word)
			continue
		}

		countTotal++
		if chunky.Tag(combined&(combined-1)) == 0 { // single bit set
			countUni++
		}

		outmap[word] = combined
	}

	// override with closed forms, hand-curated words, abbreviations
	maps.Copy(outmap, chunky.ClosedFormTags)
	maps.Copy(outmap, chunky.WordTags)
	maps.Copy(outmap, chunky.AbbreviationTags)

	if *goMode {
		tagGoName := map[chunky.Tag]string{
			chunky.TagUNK:   "chunky.TagUNK",
			chunky.TagADJ:   "chunky.TagADJ",
			chunky.TagADP:   "chunky.TagADP",
			chunky.TagADV:   "chunky.TagADV",
			chunky.TagAUX:   "chunky.TagAUX",
			chunky.TagDET:   "chunky.TagDET",
			chunky.TagCCONJ: "chunky.TagCCONJ",
			chunky.TagINTJ:  "chunky.TagINTJ",
			chunky.TagNOUN:  "chunky.TagNOUN",
			chunky.TagNUM:   "chunky.TagNUM",
			chunky.TagPART:  "chunky.TagPART",
			chunky.TagPRON:  "chunky.TagPRON",
			chunky.TagPROPN: "chunky.TagPROPN",
			chunky.TagPUNCT: "chunky.TagPUNCT",
			chunky.TagSCONJ: "chunky.TagSCONJ",
			chunky.TagSYM:   "chunky.TagSYM",
			chunky.TagVERB:  "chunky.TagVERB",
			chunky.TagX:     "chunky.TagX",
		}

		words := make([]string, 0, len(outmap))
		for w := range outmap {
			words = append(words, w)
		}
		sort.Strings(words)

		fmt.Println("// Code generated by cmd/brown-remap -go. DO NOT EDIT.")
		fmt.Println()
		fmt.Println("package tok")
		fmt.Println()
		fmt.Println(`import "github.com/client9/chunky"`)
		fmt.Println()
		fmt.Println("var wordtagmap = map[string]chunky.Tag{")
		for _, word := range words {
			bits := outmap[word]
			var parts []string
			for _, tag := range chunky.AllTags {
				if bits&tag != 0 {
					parts = append(parts, tagGoName[tag])
				}
			}
			fmt.Printf("\t%q: %s,\n", word, strings.Join(parts, " | "))
		}
		fmt.Println("}")
	} else if *csvMode {
		words := make([]string, 0, len(outmap))
		for w := range outmap {
			words = append(words, w)
		}
		sort.Strings(words)

		w := csv.NewWriter(os.Stdout)
		w.Write([]string{"word", "tags"})
		for _, word := range words {
			w.Write([]string{word, outmap[word].String()})
		}
		w.Flush()
		if err := w.Error(); err != nil {
			log.Fatalf("csv write error: %s", err)
		}
	} else {
		b, err = json.MarshalIndent(outmap, "", " ")
		if err != nil {
			log.Fatalf("unable to marshal wordmap: %s", err)
		}
		fmt.Println(string(b))
	}

	log.Printf("Total Records: %d\n", countTotal)
	log.Printf("Total UniTags: %d\n", countUni)
}
