package main

import (
	"encoding/csv"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"maps"
	"os"
	"slices"
	"sort"
	"strings"

	"github.com/client9/chunky"
)

func main() {
	csvMode := flag.Bool("csv", false, "output CSV (word,tag) instead of JSON")
	goMode := flag.Bool("go", false, "output Go source for tok/lexicon_gen.go instead of JSON")
	flag.Parse()

	// Read from Stdin
	b, err := io.ReadAll(os.Stdin)
	if err != nil {
		log.Fatalf("unable read input: %s", err)
	}

	// unserialize into wordmap
	var wordmap map[string][]string
	err = json.Unmarshal(b, &wordmap)
	if err != nil {
		log.Fatalf("unable to unmarshall Brown JSON data: %s", err)
	}

	countTotal := 0
	countUni := 0

	// convert tags
	outmap := make(map[string][]chunky.Tag, len(wordmap))
	for word, btags := range wordmap {


		// Ignore words with upper case letters.
		// they don't belong in our lexicon - often abbreviations, and limited use proper nouns
		// If they are "interesting" they'll also appear in lower case versions.
		if strings.ContainsAny(word, "ABCDEFGHIJKLMNOPQRSTUVWXYZ") {
			continue
		}
		
		// contractions and posessives don't go in
		// lexicon dictionary.
		if strings.Contains(word, "'") {
			continue
		}

		// some junk in corpus
		if strings.ContainsAny(word, "{*") {
			continue
		}

		// things with numbers are done elsewhere
		if strings.ContainsAny(word, "0123456789") {
			continue
		}

		tlist := make([]chunky.Tag,0,len(btags))
		for _, bt := range btags {
			// these are slang words or contractions
			if strings.Contains(bt, "+") {
				continue
			}
			// junk in corpus
			if bt == "NIL" {
				continue
			}
			udtag := chunky.TagFromBrownTag(bt)
			if udtag == chunky.TagUNK {
				log.Printf("brown tag of %s didn't remap for word %q", bt, word)
			}
			tlist = append(tlist, chunky.TagFromBrownTag(bt))
		}
		if len(tlist) == 0 {
			// most non-English words and junk
			log.Printf("skipped word %q: no tags", word)
			continue
		}
		
		countTotal +=1
		if len(tlist) == 1 {
			countUni += 1
		}

		slices.Sort(tlist)
		tlist = slices.Compact(tlist)
		outmap[word] = tlist
	}

	// over-ride on closed forms
	maps.Copy(outmap, chunky.ClosedFormTags)

	// add hand-curated open-category words missing from the corpus
	maps.Copy(outmap, chunky.WordTags)

	// add abbreviations
	maps.Copy(outmap, chunky.AbbreviationTags)

	if *goMode {
		// Map Tag value → Go constant name (t.String() is not always a valid identifier).
		tagGoName := map[chunky.Tag]string{
			chunky.TagUNK:   "TagUNK",
			chunky.TagADJ:   "TagADJ",
			chunky.TagADP:   "TagADP",
			chunky.TagADV:   "TagADV",
			chunky.TagAUX:   "TagAUX",
			chunky.TagDET:   "TagDET",
			chunky.TagCCONJ: "TagCCONJ",
			chunky.TagINTJ:  "TagINTJ",
			chunky.TagNOUN:  "TagNOUN",
			chunky.TagNUM:   "TagNUM",
			chunky.TagPART:  "TagPART",
			chunky.TagPRON:  "TagPRON",
			chunky.TagPROPN: "TagPROPN",
			chunky.TagPUNCT: "TagPUNCT",
			chunky.TagSCONJ: "TagSCONJ",
			chunky.TagSYM:   "TagSYM",
			chunky.TagVERB:  "TagVERB",
			chunky.TagX:     "TagX",
		}

		// Sort words for deterministic output.
		words := make([]string, 0, len(outmap))
		for w := range outmap {
			words = append(words, w)
		}
		sort.Strings(words)

		fmt.Println("// Code generated by cmd/brown-remap -go. DO NOT EDIT.")
		fmt.Println()
		fmt.Println("package tok")
		fmt.Println()
		fmt.Println(`import "github.com/client9/pos"`)
		fmt.Println()
		fmt.Println("var wordtagmap = map[string][]chunky.Tag{")
		for _, word := range words {
			tags := outmap[word]
			parts := make([]string, len(tags))
			for i, t := range tags {
				parts[i] = "chunky." + tagGoName[t]
			}
			fmt.Printf("\t%q: {%s},\n", word, strings.Join(parts, ", "))
		}
		fmt.Println("}")
	} else if *csvMode {
		// Sort words for deterministic output.
		words := make([]string, 0, len(outmap))
		for w := range outmap {
			words = append(words, w)
		}
		sort.Strings(words)

		w := csv.NewWriter(os.Stdout)
		w.Write([]string{"word", "tag"})
		for _, word := range words {
			for _, tag := range outmap[word] {
				w.Write([]string{word, tag.String()})
			}
		}
		w.Flush()
		if err := w.Error(); err != nil {
			log.Fatalf("csv write error: %s", err)
		}
	} else {
		b, err = json.MarshalIndent(outmap, "", " ")
		if err != nil {
			log.Fatalf("unable to marshal wordmap: %s", err)
		}
		fmt.Println(string(b))
	}

	log.Printf("Total Records: %d\n", countTotal)
	log.Printf("Total UniTags: %d\n", countUni)
}
