package chunky

// ClosedFormTags maps closed-class word forms to their most likely POS tags,
// covering at least 95% of observed usage.
var ClosedFormTags = map[string]Tag{
	"a":          TagDET,
	"about":      TagADP | TagADV,
	"above":      TagADP | TagADV | TagADJ,
	"across":     TagADP,
	"after":      TagADP | TagSCONJ,
	"against":    TagADP,
	"all":        TagDET | TagPRON | TagADV,
	"along":      TagADP,
	"alongside":  TagADP,
	"although":   TagSCONJ,
	"am":         TagAUX | TagPROPN | TagNOUN,
	"among":      TagADP,
	"an":         TagDET,
	"and":        TagCCONJ,
	"and/or":     TagCCONJ | TagX,
	"another":    TagDET | TagPRON,
	"any":        TagDET | TagPRON,
	"are":        TagAUX | TagVERB,
	"around":     TagADP | TagADV,
	"as":         TagADP | TagSCONJ | TagADV,
	"at":         TagADP,
	"be":         TagAUX,
	"because":    TagSCONJ,
	"been":       TagAUX,
	"before":     TagADP | TagSCONJ,
	"behind":     TagADP | TagADV,
	"being":      TagAUX,
	"below":      TagADP | TagADV,
	"between":    TagADP,
	"beyond":     TagADP,
	"both":       TagPRON | TagDET | TagCCONJ,
	"but":        TagCCONJ,
	"by":         TagADP,
	"can":        TagAUX,
	"could":      TagAUX,
	"despite":    TagSCONJ,
	"did":        TagAUX | TagVERB,
	"do":         TagAUX | TagVERB,
	"does":       TagAUX | TagVERB,
	"down":       TagADP | TagADV | TagPROPN,
	"due":        TagADP | TagADJ,
	"during":     TagADP,
	"each":       TagDET | TagPRON,
	"either":     TagCCONJ | TagDET | TagADV,
	"every":      TagDET | TagPRON,
	"except":     TagSCONJ,
	"for":        TagADP,
	"from":       TagADP,
	"get":        TagVERB | TagAUX,
	"had":        TagAUX | TagVERB,
	"half":       TagNOUN | TagADJ | TagDET,
	"has":        TagAUX | TagVERB,
	"have":       TagAUX | TagVERB,
	"having":     TagAUX | TagVERB,
	"he":         TagPRON,
	"her":        TagPRON,
	"him":        TagPRON,
	"himself":    TagPRON,
	"his":        TagPRON,
	"how":        TagSCONJ,
	"i":          TagPRON | TagPROPN,
	"if":         TagSCONJ,
	"in":         TagADP,
	"inside":     TagADP | TagADV | TagNOUN | TagADJ,
	"into":       TagADP,
	"is":         TagAUX,
	"it":         TagPRON,
	"its":        TagPRON,
	"itself":     TagPRON,
	"like":       TagADP | TagADJ,
	"may":        TagAUX | TagPROPN,
	"me":         TagPRON | TagPROPN,
	"might":      TagAUX,
	"must":       TagAUX,
	"my":         TagPRON,
	"near":       TagADP | TagPROPN | TagADJ | TagADV,
	"neither":    TagCCONJ | TagDET | TagPRON,
	"no":         TagDET | TagINTJ | TagADV | TagPROPN | TagNOUN,
	"nor":        TagCCONJ,
	"not":        TagPART,
	"of":         TagADP,
	"off":        TagADP | TagNOUN | TagADV,
	"on":         TagADP,
	"once":       TagADV | TagSCONJ,
	"onto":       TagADP,
	"or":         TagCCONJ,
	"our":        TagPRON,
	"out":        TagADP | TagADV,
	"outside":    TagADP | TagADJ | TagADV,
	"over":       TagADP,
	"past":       TagNOUN | TagADJ | TagADP,
	"per":        TagADP,
	"plus":       TagCCONJ | TagPROPN,
	"she":        TagPRON,
	"should":     TagAUX,
	"since":      TagSCONJ,
	"so":         TagADV | TagSCONJ,
	"some":       TagDET | TagPRON,
	"someone":    TagPRON,
	"something":  TagPRON,
	"than":       TagADP,
	"that":       TagPRON | TagSCONJ | TagDET,
	"the":        TagDET,
	"their":      TagPRON,
	"them":       TagPRON,
	"themselves": TagPRON,
	"there":      TagPRON | TagADV,
	"these":      TagDET | TagPRON,
	"they":       TagPRON,
	"this":       TagDET | TagPRON,
	"those":      TagPRON | TagDET,
	"though":     TagSCONJ,
	"through":    TagADP,
	"throughout": TagADP,
	"to":         TagADP | TagPART,
	"toward":     TagADP,
	"towards":    TagADP,
	"twice":      TagADV | TagDET,
	"under":      TagADP,
	"unlike":     TagADP,
	"until":      TagADP | TagSCONJ,
	"up":         TagADP | TagNOUN | TagADV,
	"upon":       TagSCONJ,
	"via":        TagADP,
	"was":        TagAUX,
	"we":         TagPRON,
	"were":       TagAUX,
	"what":       TagPRON | TagDET,
	"when":       TagSCONJ,
	"where":      TagSCONJ,
	"whereas":    TagSCONJ,
	"whereby":    TagSCONJ,
	"whether":    TagSCONJ,
	"which":      TagPRON,
	"while":      TagSCONJ,
	"who":        TagPRON,
	"whom":       TagPRON,
	"whose":      TagDET,
	"why":        TagSCONJ,
	"will":       TagAUX | TagNOUN,
	"with":       TagADP,
	"within":     TagADP,
	"without":    TagADP,
	"would":      TagAUX,
	"yet":        TagADV | TagCCONJ,
	"you":        TagPRON,
	"your":       TagPRON,
}
