package tok

import "strings"

// wordHandlers maps lowercase word forms to their per-token disambiguation handler.
// DisambiguateWords uses a single map lookup instead of calling every handler for every token.
// Every word form that has special disambiguation rules must appear here explicitly.
var wordHandlers = map[string]func([]Token, int){
	"about":         disambiguatePrepositions,
	"above":         disambiguateAbove,
	"adds":          disambiguateVerbForms,
	"after":         disambiguateAfter,
	"all":           disambiguateQuantifiers,
	"alone":         disambiguateAdjAdvDefault,
	"another":       disambiguateDetPron,
	"any":           disambiguateAnyAll,
	"argues":        disambiguateVerbForms,
	"around":        disambiguatePrepositions,
	"as":            disambiguateAs,
	"back":          disambiguateBack,
	"bad":           disambiguateAdjAdvDefault,
	"before":        disambiguateAfter,
	"behind":        disambiguatePrepositions,
	"below":         disambiguatePrepositions,
	"best":          disambiguateBest,
	"better":        disambiguateBetter,
	"both":          disambiguateQuantifiers,
	"brand":         disambiguateAdvNoun,
	"brings":        disambiguateVerbForms,
	"calls":         disambiguateVerbForms,
	"clean":         disambiguateAdjAdvDefault,
	"cleaner":       disambiguateAdjAdvDefault,
	"cleanest":      disambiguateAdjAdvDefault,
	"clear":         disambiguateClear,
	"closer":        disambiguateAdjAdvDefault,
	"closest":       disambiguateAdjAdvDefault,
	"cold":          disambiguateAdjAdvDefault,
	"colder":        disambiguateAdjAdvDefault,
	"coldest":       disambiguateAdjAdvDefault,
	"comes":         disambiguateVerbForms,
	"complete":      disambiguateOwn,
	"correct":       disambiguateOwn,
	"corresponding": disambiguateOwn,
	"dead":          disambiguateDead,
	"deep":          disambiguateAdjAdvDefault,
	"deeper":        disambiguateAdjAdvDefault,
	"deepest":       disambiguateAdjAdvDefault,
	"despite":       disambiguateSCONJasADP,
	"direct":        disambiguateAdjAdvDefault,
	"down":          disambiguateDown,
	"dry":           disambiguateOwn,
	"due":           disambiguateLike,
	"each":          disambiguateEachAll,
	"earlier":       disambiguateLaterGroup,
	"earliest":      disambiguateAdjAdvDefault,
	"early":         disambiguateEarlyLate,
	"east":          disambiguateDirectionals,
	"either":        disambiguateQuantifiers,
	"elaborate":     disambiguateOwn,
	"engaging":      disambiguateOwn,
	"enough":        disambiguateMore,
	"far":           disambiguateAdjAdvDefault,
	"farthest":      disambiguateAdjAdvDefault,
	"fast":          disambiguateAdjAdvDefault,
	"faster":        disambiguateAdjAdvDefault,
	"fastest":       disambiguateAdjAdvDefault,
	"fell":          disambiguateVerbForms,
	"final":         disambiguateHalf,
	"first":         disambiguateOrdinals,
	"flat":          disambiguateAdjAdvDefault,
	"following":     disambiguateFollowing,
	"forward":       disambiguateAdjAdvDefault,
	"free":          disambiguateFree,
	"frequent":      disambiguateOwn,
	"further":       disambiguateLaterGroup,
	"furthest":      disambiguateAdjAdvDefault,
	"gives":         disambiguateVerbForms,
	"goes":          disambiguateVerbForms,
	"good":          disambiguateAdjAdvDefault,
	"great":         disambiguateAdjAdvDefault,
	"greater":       disambiguateAdjAdvDefault,
	"greatest":      disambiguateAdjAdvDefault,
	"half":          disambiguateHalf,
	"hard":          disambiguateAdjAdvDefault,
	"harder":        disambiguateAdjAdvDefault,
	"hardest":       disambiguateAdjAdvDefault,
	"high":          disambiguateHigh,
	"higher":        disambiguateHigh,
	"highest":       disambiguateHigh,
	"holds":         disambiguateVerbForms,
	"ill":           disambiguateAdjAdvDefault,
	"individual":    disambiguateHalf,
	"inside":        disambiguateAbove,
	"lasting":       disambiguateOwn,
	"late":          disambiguateEarlyLate,
	"later":         disambiguateLaterGroup,
	"latest":        disambiguateAdjAdvDefault,
	"leads":         disambiguateVerbForms,
	"leaves":        disambiguateVerbForms,
	"less":          disambiguateMore,
	"like":          disambiguateLike,
	"likely":        disambiguateLikely,
	"little":        disambiguateOnly,
	"live":          disambiguateOwn,
	"long":          disambiguateLong,
	"longer":        disambiguateLong,
	"longest":       disambiguateLong,
	"lot":           disambiguateAdvNoun,
	"loud":          disambiguateAdjAdvDefault,
	"louder":        disambiguateAdjAdvDefault,
	"loudest":       disambiguateAdjAdvDefault,
	"low":           disambiguateAdjAdvDefault,
	"lower":         disambiguateAdjAdvDefault,
	"lowest":        disambiguateAdjAdvDefault,
	"makes":         disambiguateVerbForms,
	"marked":        disambiguateOwn,
	"may":           disambiguateMay,
	"means":         disambiguateVerbForms,
	"mine":          disambiguateMine,
	"more":          disambiguateMore,
	"most":          disambiguateMore,
	"much":          disambiguateMore,
	"near":          disambiguateDown,
	"neat":          disambiguateAdjAdvDefault,
	"neater":        disambiguateAdjAdvDefault,
	"neatest":       disambiguateAdjAdvDefault,
	"needs":         disambiguateVerbForms,
	"neither":       disambiguateQuantifiers,
	"north":         disambiguateDirectionals,
	"northeast":     disambiguateDirectionals,
	"northwest":     disambiguateDirectionals,
	"off":           disambiguateParticles,
	"once":          disambiguateOnce,
	"one":           disambiguateOne,
	"only":          disambiguateOnly,
	"out":           disambiguatePrepositions,
	"outside":       disambiguateAbove,
	"overseas":      disambiguateAdjAdvDefault,
	"own":           disambiguateOwn,
	"past":          disambiguatePast,
	"pending":       disambiguateLike,
	"plain":         disambiguateAdjAdvDefault,
	"plans":         disambiguateVerbForms,
	"plus":          disambiguatePlus,
	"prior":         disambiguatePrior,
	"pro":           disambiguatePro,
	"pursuant":      disambiguateLike,
	"quick":         disambiguateAdjAdvDefault,
	"quicker":       disambiguateAdjAdvDefault,
	"quickest":      disambiguateAdjAdvDefault,
	"real":          disambiguateAdjAdvDefault,
	"remains":       disambiguateVerbForms,
	"respecting":    disambiguateSave,
	"right":         disambiguateRight,
	"rose":          disambiguateVerbForms,
	"rough":         disambiguateAdjAdvDefault,
	"rougher":       disambiguateAdjAdvDefault,
	"roughest":      disambiguateAdjAdvDefault,
	"runs":          disambiguateVerbForms,
	"save":          disambiguateSave,
	"say":           disambiguateVerbForms,
	"says":          disambiguateVerbForms,
	"second":        disambiguateOrdinals,
	"secure":        disambiguateOwn,
	"separate":      disambiguateOwn,
	"short":         disambiguateAdjAdvDefault,
	"shorter":       disambiguateAdjAdvDefault,
	"shortest":      disambiguateAdjAdvDefault,
	"shows":         disambiguateVerbForms,
	"since":         disambiguateSCONJasADP,
	"slow":          disambiguateAdjAdvDefault,
	"slower":        disambiguateAdjAdvDefault,
	"slowest":       disambiguateAdjAdvDefault,
	"small":         disambiguateAdjAdvDefault,
	"smaller":       disambiguateAdjAdvDefault,
	"smallest":      disambiguateAdjAdvDefault,
	"smooth":        disambiguateOwn,
	"so":            disambiguateSo,
	"soft":          disambiguateAdjAdvDefault,
	"softer":        disambiguateAdjAdvDefault,
	"softest":       disambiguateAdjAdvDefault,
	"some":          disambiguateDetPron,
	"south":         disambiguateDirectionals,
	"southeast":     disambiguateDirectionals,
	"southwest":     disambiguateDirectionals,
	"steady":        disambiguateAdjAdvDefault,
	"such":          disambiguateSuch,
	"sure":          disambiguateAdjAdvDefault,
	"takes":         disambiguateVerbForms,
	"that":          disambiguateThat,
	"then":          disambiguateThen,
	"there":         disambiguateThere,
	"these":         disambiguateDetPron,
	"thick":         disambiguateAdjAdvDefault,
	"thicker":       disambiguateAdjAdvDefault,
	"thickest":      disambiguateAdjAdvDefault,
	"third":         disambiguateOrdinals,
	"this":          disambiguateDetPron,
	"those":         disambiguateDetPron,
	"tight":         disambiguateAdjAdvDefault,
	"tighter":       disambiguateAdjAdvDefault,
	"tightest":      disambiguateAdjAdvDefault,
	"to":            disambiguateTo,
	"turns":         disambiguateVerbForms,
	"twice":         disambiguateMore,
	"u":             disambiguateU,
	"underground":   disambiguateAdjAdvDefault,
	"until":         disambiguateAfter,
	"up":            disambiguateUpAll,
	"upon":          disambiguateSCONJasADP,
	"varying":       disambiguateOwn,
	"wants":         disambiguateVerbForms,
	"warm":          disambiguateOwn,
	"way":           disambiguateAdvNoun,
	"well":          disambiguateWell,
	"west":          disambiguateDirectionals,
	"what":          disambiguateDetPron,
	"wide":          disambiguateAdjAdvDefault,
	"wider":         disambiguateAdjAdvDefault,
	"widest":        disambiguateAdjAdvDefault,
	"will":          disambiguateWill,
	"wrong":         disambiguateAdjAdvDefault,
	"yet":           disambiguateYet,
}

// disambiguateUpAll chains the particle handler (ADP|ADV) with the NOUN-bit handler.
func disambiguateUpAll(tokens []Token, i int) {
	disambiguateParticles(tokens, i)
	disambiguateUp(tokens, i)
}

// disambiguateEachAll chains quantifier and det/pron handlers for "each".
func disambiguateEachAll(tokens []Token, i int) {
	disambiguateQuantifiers(tokens, i)
	disambiguateDetPron(tokens, i)
}

// disambiguateAnyAll chains quantifier and det/pron handlers for "any".
func disambiguateAnyAll(tokens []Token, i int) {
	disambiguateQuantifiers(tokens, i)
	disambiguateDetPron(tokens, i)
}

// DisambiguateWords applies all word-specific disambiguation in a single pass.
// It must run after LexicalTag and TagUnknowns, and before sentence segmentation
// and context disambiguation.
//
// ContractionFragments and ApostropheS run as separate pre-passes: the former
// has no tag guard, the latter mutates neighboring tokens and must complete
// before the main pass reads neighbors.
//
// To add a new word-specific disambiguator: implement a func([]Token, int) helper
// and register it in wordHandlers above.
func DisambiguateWords(tokens []Token) []Token {
	tokens = DisambiguateContractionFragments(tokens)
	tokens = DisambiguateApostropheS(tokens)
	for i := range tokens {
		lw := strings.ToLower(tokens[i].Word)
		if h, ok := wordHandlers[lw]; ok {
			h(tokens, i)
		}
		disambiguateAdjVerb(tokens, i)
	}
	return tokens
}
